/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "GOOGLE_AUTH_PROVIDER_X509_CERT_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_AUTH_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_X509_CERT_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PRIVATE_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_PROJECT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_TOKEN_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_UNIVERSE_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SPREADSHEET_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}