# run build and unit test every PR to main branch

name: Pull Request CI
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install Deps (immutable)
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Run Unit Tests
        run: pnpm test:coverage
